### ISSUE TITLE
highlight_line

### ISSUE THREAD

**Issue by QuentinRoy** [jwortmann/brackets-color-scheme#1] opened 2015-06-03 15:14 UTC
Nice work! Thanks!

Just a detail, highligh_line does not work.

**Comment by jwortmann** [comment] 2021-10-27 14:20
I'm sorry to answer only decades after this issue was created, and I don't know if you're still using Sublime Text or this color scheme. But I assume the described problem was caused by a bug in Sublime Text, that the line highlighting didn't work when the gutter with the line numbers was disabled. This bug has finally been fixed in the latest ST build which was released yesterday, so I guess this issue can be closed now ;)

**Closed as completed by jwortmann** 2021-10-27 14:20 UTC
